agent = "goose"
[projects."/home/tekkamelon"]
trust_level = "trusted"

[projects."/home/tekkamelon/Documents/github/vroid_companion"]
trust_level = "trusted"

[projects."/home/tekkamelon/Documents/github/sh-mpd"]
trust_level = "trusted"

[cli]
first_launch_complete = true


[[agents]]
name = "goose"
slug = "goose"

[agents.distribution.local]
command = "goose"
args = ["acp"]

[[agents]]
name = "grok"
slug = "grok"

[agents.distribution.local]
command = "grok"
args = ["agent", "stdio"]

[default_models]
goose = "preview/Kimi-K2.6"
grok = "grok-4.5"
